config/routes.rb
Rails.application.routes.draw do
  resources :words
  root 'pictures#new'
  resources :pictures
  post 'check_halal', to: 'pictures#create_from_android'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id         :integer          not null, primary key
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string
#

class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  def check_halal
    Vision.new(image.path).check
  end
end

app/models/word.rb
# == Schema Information
#
# Table name: words
#
#  id         :integer          not null, primary key
#  name       :string
#  english    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  protect_from_forgery except: %i[create create_from_android]
  before_action :set_picture, only: %i[show edit update destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    result = @picture.check_halal
    @picture.status = result[:status]

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: result[:status] }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_from_android
    @picture = Picture.new(image: params[:image])
    result = @picture.check_halal
    @picture.status = result[:status]

    if @picture.save
      render json: { image: @picture.image.url, result: result[:status] }
    else
      render json: @picture.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :status)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to words_url }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to words_url }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :english)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindHalalApiPrototype</title>
    <%= csrf_meta_tags %>
    <meta  name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.file_field :image, id: :picture_image, class: 'form-control-file' %>
  </div>

  <div class="actions">
    <%= form.submit value: 'check', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Check Halal', new_picture_path, class: 'btn btn-primary' %>
<br><br>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <th scope="row"><%= picture.id %></th>
        <td><%= image_tag picture.image.url, class: "img-thumbnail" %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pictures/new.html.erb
<h1>Check Halal Food</h1>

<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<p><%= @picture.status %></p>
<%= image_tag @picture.image.to_s, class: "img-thumbnail" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
  <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'FindHalal', root_path, class: 'navbar-brand' %>

  <div class="navbar-collapse collapse" id="navbarsExampleDefault" aria-expanded="false">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to  pictures_path, class: 'nav-link' do %>
          Index<span class="sr-only"></span>
        <% end %>
      </li>
      <li class="nav-item active">
        <%= link_to  words_path, class: 'nav-link' do %>
          Dictionary<span class="sr-only"></span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <div class="input-field">
    <%= form.label 'Japanese', class: 'active' %>
    <%= form.text_field :name, id: :word_name %>
  </div>

  <div class="input-field">
    <%= form.label :english, class: 'active' %>
    <%= form.text_field :english, id: :word_english %>
  </div>

  <button class="btn waves-effect waves-light" type="submit" name="commit">Save</button>
<% end %>

app/views/words/edit.html.erb
<%= render 'form', word: @word %>

app/views/words/index.html.erb
<table class="table striped">
  <thead>
    <tr>
      <th>Japanese</th>
      <th>English</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.name %></td>
        <td><%= word.english %></td>
        <td><%= link_to 'Edit', edit_word_path(word), class: 'waves-effect waves-light btn blue' %></td>
        <td><%= link_to 'Delete', word, method: :delete, data: { confirm: 'Are you sure?' }, class: 'waves-effect waves-light btn red' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="fixed-action-btn">
  <%= link_to new_word_path, class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>
<br>

app/views/words/new.html.erb
<%= render 'form', word: @word %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word.name %>
</p>

<p>
  <strong>English:</strong>
  <%= @word.english %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>